import { User, Job, Application, Message, Conversation } from './types';

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
const in3Days = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);

export const mockCurrentUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  role: 'contractor',
  trustStatus: 'verified',
  rating: 4.8,
  reliabilityRating: 4.9,
  completedJobs: 12,
  memberSince: new Date('2023-01-15'),
  businessName: 'Johnson Construction',
  abn: '12345678901',
  primaryTrade: 'Carpenter',
  createdAt: new Date('2023-01-15'),
};

export const demoUsers = {
  admin: {
    id: 'demo-admin',
    name: 'Admin Demo',
    email: 'admin@test.com',
    password: 'password',
    role: 'admin' as const,
    trustStatus: 'verified' as const,
    rating: 5.0,
    completedJobs: 0,
    memberSince: new Date('2023-01-01'),
    createdAt: new Date('2023-01-01'),
  },
  contractor: {
    id: 'demo-contractor',
    name: 'Contractor Demo',
    email: 'contractor@test.com',
    password: 'password',
    role: 'contractor' as const,
    trustStatus: 'verified' as const,
    rating: 4.8,
    reliabilityRating: 4.9,
    completedJobs: 12,
    memberSince: new Date('2023-01-15'),
    businessName: 'Demo Construction Co',
    abn: '12345678901',
    primaryTrade: 'Electrician',
    createdAt: new Date('2023-01-15'),
  },
  subcontractor: {
    id: 'demo-subcontractor',
    name: 'Subcontractor Demo',
    email: 'subcontractor@test.com',
    password: 'password',
    role: 'subcontractor' as const,
    trustStatus: 'verified' as const,
    bio: 'Licensed electrician with 10+ years experience',
    rating: 4.9,
    reliabilityRating: 5.0,
    completedJobs: 28,
    memberSince: new Date('2022-06-10'),
    primaryTrade: 'Electrician',
    trades: ['Commercial Electrical', 'Solar Installation'],
    location: 'Richmond',
    radius: 15,
    availability: {
      Monday: true,
      Tuesday: true,
      Wednesday: true,
      Thursday: true,
      Friday: true,
      Saturday: false,
      Sunday: false,
    },
    createdAt: new Date('2022-06-10'),
    subcontractorPlan: 'PRO_10' as const,
    subcontractorSubStatus: 'ACTIVE' as const,
    subcontractorSubRenewsAt: new Date('2025-01-31'),
    subcontractorPreferredRadiusKm: 50,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: true,
    subcontractorAlertChannelSms: true,
    subcontractorAvailabilityHorizonDays: 60,
    subcontractorWorkAlertsEnabled: true,
    subcontractorWorkAlertInApp: true,
    subcontractorWorkAlertEmail: true,
    subcontractorWorkAlertSms: false,
    subcontractorAvailabilityBroadcastEnabled: true,
    smsOptInPromptShown: false,
  },
  qaElectrician: {
    id: 'qa-electrician',
    name: 'QA Test - Electrician',
    email: 'test+electrician@tradebid.com.au',
    password: 'password',
    role: 'subcontractor' as const,
    trustStatus: 'verified' as const,
    bio: 'QA test account for Electrician trade visibility testing',
    rating: 4.8,
    reliabilityRating: 4.9,
    completedJobs: 15,
    memberSince: new Date('2024-01-01'),
    primaryTrade: 'Electrician',
    trades: ['Commercial Electrical', 'Residential Electrical'],
    location: 'Melbourne',
    radius: 50,
    createdAt: new Date('2024-01-01'),
    subcontractorPlan: 'PRO_10' as const,
    subcontractorSubStatus: 'ACTIVE' as const,
    subcontractorSubRenewsAt: new Date('2025-12-31'),
    subcontractorPreferredRadiusKm: 50,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: true,
    subcontractorAlertChannelSms: false,
  },
  qaPlumber: {
    id: 'qa-plumber',
    name: 'QA Test - Plumber',
    email: 'test+plumber@tradebid.com.au',
    password: 'password',
    role: 'subcontractor' as const,
    trustStatus: 'verified' as const,
    bio: 'QA test account for Plumber trade visibility testing',
    rating: 4.8,
    reliabilityRating: 4.9,
    completedJobs: 15,
    memberSince: new Date('2024-01-01'),
    primaryTrade: 'Plumber',
    trades: ['Commercial Plumbing', 'Residential Plumbing'],
    location: 'Melbourne',
    radius: 50,
    createdAt: new Date('2024-01-01'),
    subcontractorPlan: 'PRO_10' as const,
    subcontractorSubStatus: 'ACTIVE' as const,
    subcontractorSubRenewsAt: new Date('2025-12-31'),
    subcontractorPreferredRadiusKm: 50,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: true,
    subcontractorAlertChannelSms: false,
  },
  qaCarpenter: {
    id: 'qa-carpenter',
    name: 'QA Test - Carpenter',
    email: 'test+carpenter@tradebid.com.au',
    password: 'password',
    role: 'subcontractor' as const,
    trustStatus: 'verified' as const,
    bio: 'QA test account for Carpenter trade visibility testing',
    rating: 4.8,
    reliabilityRating: 4.9,
    completedJobs: 15,
    memberSince: new Date('2024-01-01'),
    primaryTrade: 'Carpenter',
    trades: ['Formwork', 'Framing', 'Finishing'],
    location: 'Melbourne',
    radius: 50,
    createdAt: new Date('2024-01-01'),
    subcontractorPlan: 'PRO_10' as const,
    subcontractorSubStatus: 'ACTIVE' as const,
    subcontractorSubRenewsAt: new Date('2025-12-31'),
    subcontractorPreferredRadiusKm: 50,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: true,
    subcontractorAlertChannelSms: false,
  },
  qaPainter: {
    id: 'qa-painter',
    name: 'QA Test - Painter',
    email: 'test+painter@tradebid.com.au',
    password: 'password',
    role: 'subcontractor' as const,
    trustStatus: 'verified' as const,
    bio: 'QA test account for Painter & Decorator trade visibility testing',
    rating: 4.8,
    reliabilityRating: 4.9,
    completedJobs: 15,
    memberSince: new Date('2024-01-01'),
    primaryTrade: 'Painter & Decorator',
    trades: ['Interior Painting', 'Exterior Painting', 'Commercial Painting'],
    location: 'Melbourne',
    radius: 50,
    createdAt: new Date('2024-01-01'),
    subcontractorPlan: 'PRO_10' as const,
    subcontractorSubStatus: 'ACTIVE' as const,
    subcontractorSubRenewsAt: new Date('2025-12-31'),
    subcontractorPreferredRadiusKm: 50,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: true,
    subcontractorAlertChannelSms: false,
  },
  qaAdmin: {
    id: 'qa-admin',
    name: 'QA Test - Admin',
    email: 'test+admin@tradebid.com.au',
    password: 'password',
    role: 'admin' as const,
    trustStatus: 'verified' as const,
    rating: 5.0,
    reliabilityRating: 5.0,
    completedJobs: 0,
    memberSince: new Date('2024-01-01'),
    createdAt: new Date('2024-01-01'),
  },
};

export const mockUsers: User[] = [
  mockCurrentUser,
  demoUsers.admin,
  demoUsers.contractor,
  demoUsers.subcontractor,
  demoUsers.qaElectrician,
  demoUsers.qaPlumber,
  demoUsers.qaCarpenter,
  demoUsers.qaPainter,
  demoUsers.qaAdmin,
  {
    id: 'user-2',
    name: 'Sam Clarke',
    email: 'sam@example.com',
    role: 'subcontractor',
    trustStatus: 'verified',
    bio: 'Licensed electrician with 10+ years experience',
    rating: 4.9,
    reliabilityRating: 5.0,
    completedJobs: 28,
    memberSince: new Date('2022-06-10'),
    primaryTrade: 'Electrician',
    trades: ['Commercial Electrical', 'Solar Installation'],
    location: 'Richmond',
    radius: 15,
    availability: {
      Monday: true,
      Tuesday: true,
      Wednesday: true,
      Thursday: true,
      Friday: true,
      Saturday: false,
      Sunday: false,
    },
    createdAt: new Date('2022-06-10'),
    subcontractorPlan: 'PRO_10',
    subcontractorSubStatus: 'ACTIVE',
    subcontractorSubRenewsAt: new Date('2025-02-10'),
    subcontractorPreferredRadiusKm: 75,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: true,
    subcontractorAlertChannelSms: false,
    subcontractorAvailabilityHorizonDays: 60,
    subcontractorWorkAlertsEnabled: true,
    subcontractorWorkAlertInApp: true,
    subcontractorWorkAlertEmail: true,
    subcontractorWorkAlertSms: false,
    subcontractorAvailabilityBroadcastEnabled: true,
    smsOptInPromptShown: false,
  },
  {
    id: 'user-3',
    name: 'Jordan Smith',
    email: 'jordan@example.com',
    role: 'subcontractor',
    trustStatus: 'approved',
    bio: 'Plumber, gas fitter, experienced',
    rating: 4.6,
    reliabilityRating: 4.5,
    completedJobs: 15,
    memberSince: new Date('2023-03-20'),
    primaryTrade: 'Plumber',
    trades: ['Residential Plumbing', 'Gas Fitting'],
    location: 'Fitzroy',
    radius: 20,
    availability: {
      Monday: true,
      Tuesday: true,
      Wednesday: false,
      Thursday: true,
      Friday: true,
      Saturday: true,
      Sunday: false,
    },
    createdAt: new Date('2023-03-20'),
    subcontractorPlan: 'NONE',
    subcontractorSubStatus: 'NONE',
    subcontractorPreferredRadiusKm: 15,
    subcontractorAlertsEnabled: true,
    subcontractorAlertChannelInApp: true,
    subcontractorAlertChannelEmail: false,
    subcontractorAlertChannelSms: false,
    subcontractorAvailabilityHorizonDays: 14,
    subcontractorWorkAlertsEnabled: true,
    subcontractorWorkAlertInApp: true,
    subcontractorWorkAlertEmail: true,
    subcontractorWorkAlertSms: false,
    subcontractorAvailabilityBroadcastEnabled: false,
    smsOptInPromptShown: false,
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    contractorId: 'user-1',
    title: 'Electrical Rewire - Kitchen & Living Room',
    description: 'Full rewire of kitchen and living room. 240V circuits needed for new appliances. Works needs to be completed before Christmas.',
    tradeCategory: 'Electrician',
    location: 'Richmond',
    postcode: '3121',
    dates: [tomorrow, new Date(tomorrow.getTime() + 86400000)],
    startTime: '08:00',
    duration: 2,
    payType: 'fixed',
    rate: 2400,
    status: 'open',
    createdAt: now,
  },
  {
    id: 'job-2',
    contractorId: 'user-1',
    title: 'Bathroom Plumbing Installation',
    description: 'Install new vanity, toilet, and shower. Relocate pipes. New tile work not included.',
    tradeCategory: 'Plumber',
    location: 'Fitzroy',
    postcode: '3065',
    dates: [in3Days],
    startTime: '09:00',
    duration: 1,
    payType: 'hourly',
    rate: 85,
    status: 'accepted',
    selectedSubcontractor: 'user-3',
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'job-3',
    contractorId: 'user-1',
    title: 'Solar Panel Installation',
    description: '6.6kW solar system installation. Roof assessment included.',
    tradeCategory: 'Electrician',
    location: 'Richmond',
    postcode: '3121',
    dates: [new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)],
    startTime: '07:00',
    duration: 1,
    payType: 'fixed',
    rate: 3500,
    status: 'accepted',
    selectedSubcontractor: 'user-2',
    createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    subcontractorId: 'user-2',
    status: 'applied',
    appliedAt: new Date(now.getTime() - 30 * 60 * 1000),
    message: 'I have 10+ years of electrical experience and can start immediately.',
  },
  {
    id: 'app-2',
    jobId: 'job-1',
    subcontractorId: 'user-3',
    status: 'applied',
    appliedAt: new Date(now.getTime() - 15 * 60 * 1000),
    message: 'Available for both days, happy to help.',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    jobId: 'job-2',
    contractorId: 'user-1',
    subcontractorId: 'user-3',
    updatedAt: new Date(now.getTime() - 5 * 60 * 1000),
    createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'conv-2',
    jobId: 'job-3',
    contractorId: 'user-1',
    subcontractorId: 'user-2',
    updatedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'user-1',
    text: 'Hi Jordan, I have a bathroom plumbing job in Fitzroy starting in 3 days. Are you interested?',
    createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'user-1',
    text: 'I selected you for this job. Please confirm if you can do Mon 18th Dec.',
    isSystemMessage: false,
    createdAt: new Date(now.getTime() - 50 * 60 * 1000),
  },
  {
    id: 'msg-3',
    conversationId: 'conv-2',
    senderId: 'user-2',
    text: 'Perfect! I can start next week. Do you need any roof assessment before the install?',
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
];

export const mockReviews: any[] = [];

export const mockData = {
  users: mockUsers,
  jobs: mockJobs,
  applications: mockApplications,
  conversations: mockConversations,
  messages: mockMessages,
  reviews: mockReviews,
  auditLogs: [],
  adminNotes: [],
};
